[tox]
envlist = 
    py{310,311}-pandas{15,20,21,22,23}
    py312-pandas{21,22,23}
    py313-pandas{22,23}
    py314-pandas23
    latest

[testenv]
package = wheel

deps =
    pytest
    requests>=2.25
    termcolor>=2.0
    lxml>=4.9
    numpy>=1.23,<2.0

    pandas15: pandas>=1.5,<2.0
    pandas20: pandas>=2.0,<2.1
    pandas21: pandas>=2.1,<2.2
    pandas22: pandas>=2.2,<2.3
    pandas23: pandas>=2.3,<3.0

commands =
    pytest -v


[testenv:latest]
package = wheel

deps =
    pytest
    requests>=2.25
    termcolor>=2.0
    lxml

    pandas>=2.3
    numpy>=2.0

commands =
    pytest -v